webapp/searched/forms.py
from flask_wtf import FlaskForm as Form
from flask_wtf import RecaptchaField
from wtforms import StringField, PasswordField, BooleanField, SubmitField,SelectField
from wtforms.validators import DataRequired, Length, EqualTo, URL

class SearchForm(Form):
    
    bar_search = StringField('Searched:', validators=[DataRequired()])
    submit = SubmitField('Submit')

webapp/__init__.py
from flask import Flask

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from sqlalchemy import create_engine
from sqlalchemy import MetaData


migrate = Migrate()

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))



def page_not_found(error):
    return render_template('404.html'), 404

def create_app(object_name):
    
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    migrate.init_app(app, db, render_as_batch=True)

   

  
    from .system import create_module as system_create_module
    from .auth import create_module as auth_create_module
    from .searched import create_module as searched_create_module
    from .main import create_module as main_create_module
    auth_create_module(app)
    system_create_module(app)
    searched_create_module(app)
    main_create_module(app)

    return app

webapp/main/__init__.py
def create_module(app, **kwargs):
    from .controllers import main_blueprint
    app.register_blueprint(main_blueprint)

webapp/main/controllers.py
from flask import Blueprint, redirect, url_for, render_template

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@main_blueprint.route('/')
def index():
    return redirect(url_for('system.portfs'))

webapp/searched/__init__.py
def create_module(app, **kwargs):
    from .controllers import searched_blueprint
    app.register_blueprint(searched_blueprint)

webapp/searched/controllers.py
from datetime import datetime
from sqlalchemy import desc, func
from flask import render_template, Blueprint, flash, redirect, url_for, current_app, abort, jsonify,request
from flask_login import login_required, current_user
from ..system.models import db, Portfs, Events, Customers, Cars,Departments, ProjectData
from ..auth.models import Users,Role
from ..auth import has_role
from werkzeug.security import generate_password_hash, check_password_hash
from .forms import SearchForm
from ..system.forms import  PortForm, EventsForm, CustomerForm,CarsForm,ProjectDataForm
from sqlalchemy import or_

searched_blueprint = Blueprint(
    'searched',
    __name__,
    template_folder='../templates'
)


@searched_blueprint.context_processor
def base():
    form=SearchForm()
    return dict(form=form)

@searched_blueprint.route('/search/<adress>',methods=['GET', 'POST'])
def search(adress): 
    
    form = SearchForm()
        

    if form.validate_on_submit() or True:
        
        searched = form.bar_search.data
        current_page=str(adress)

        

        models={1:Customers,2:Events,3:Cars,4:Portfs,5:Departments, 6:Users, 7:ProjectData}
        pages={1:'system.customers',2:'system.events',3:'system.cars',4:'system.portfs',5:'system.departments',6:'auth.users',7:'system.projectdata'}

        for key_model in models:
            model = models[key_model]

            for key_page in pages:
                page=pages[key_page]

                if (len(str(searched))> 1) and (current_page==page) and (key_model == key_page) and searched != None: 
                   
                    attrs= dir(model.query.first())          
                    

                    
                    if page == 'auth.users':
                        attrs_filtered = list(filter(lambda x: x.find('_')<0 and not(any([x in ['registry','query','metadata','roles']])), attrs))
                        
                        model_attrs = [[model.query.filter(getattr(model, i).like('%' +searched+'%' )),getattr(model, i)]
                                        for i in attrs_filtered 
                                        if model.query.filter(getattr(model, i).like('%' + searched +'%' )).first() != None]                  
                    else:
                        attrs_filtered = list(filter(lambda x: x.find('_')<0 and not(any([x in ['registry','query','metadata']])), attrs))
                        model_attrs = [[model.query.filter(getattr(model, i).like('%' +searched+'%' )),getattr(model, i)]
                                        for i in attrs_filtered 
                                        if model.query.filter(getattr(model, i).like('%' + searched +'%' )).first() != None]
                    
                    
                    len_model_attrs=[len(i[0].all()) for i in model_attrs]
                    max_index=len_model_attrs.index(max(len_model_attrs))

                    the_attr= model_attrs[max_index][1]
                   
                    
                    models_filtered = model_attrs[max_index][0].order_by(the_attr)
                    
                     
                    return render_template('Search.html', our_models=models_filtered,page=page)
                    
                
                elif searched == None and (current_page==page) and (key_model == key_page):

                    attrs= dir(model.query.first())          
                    attrs_filtered = list(filter(lambda x: x.find('_')<0 and not(any([x in ['registry','query','metadata']])), attrs))

                    all_models = model.query.all()
                    all_category=[]
                    for model in all_models:
                        for attr in attrs_filtered:
                            all_category.append(str(getattr(model, attr)))



                    return jsonify(all_category)

   

webapp/system/__init__.py
def create_module(app, **kwargs):
    from .controllers import system_blueprint
    app.register_blueprint(system_blueprint)

webapp/system/controllers.py
from datetime import datetime
from sqlalchemy import desc, func
from flask import render_template, Blueprint, flash, redirect, url_for, current_app, abort, request
from flask_login import login_required, current_user
from .models import db, Portfs, Events, Customers, Cars, Departments, ProjectData
from ..auth.models import Users,Role
from ..auth import has_role
from werkzeug.security import generate_password_hash, check_password_hash
from ..searched.forms import SearchForm
from .forms import  PortForm, EventsForm, CustomerForm,CarsForm, DepartmentsForm, ProjectDataForm


system_blueprint = Blueprint(
    'system',
    __name__,
    template_folder='../templates'
)


@system_blueprint.route('/projectdata/projectdataDelete/<int:id>',methods=['GET', 'POST'])
def projectdataDelete(id):
    
    form= ProjectDataForm()
    projectdata_to_delete = ProjectData.query.get_or_404(id)
    
    try:
        db.session.delete(projectdata_to_delete)
        db.session.commit()
        flash("Project data deleted")
        
        our_projectdata=ProjectData.query.order_by(ProjectData.id)
        return redirect(url_for('system.projectdata'))
    except:
        flash('There was a problem deleting your event')
        return redirect(url_for('system.projectdata'))


@system_blueprint.route('/projectdata/projectdataAdd',methods=['POST', 'GET'])
def projectdataAdd():
    
    form=ProjectDataForm()
    carid= request.form.get('Cars')
    usersid= request.form.get('Operations Manager')
    deparmentsid= request.form.get('Departments')
    
    if form.validate_on_submit():

        
        
        car = Cars.query.get_or_404(int(carid))
        department = Departments.query.get_or_404(int(deparmentsid))
        user = Users.query.get_or_404(int(usersid))

        projectdata = ProjectData(amount=form.amount.data,observations=form.observations.data, solution=form.solution.data)
        
        car.projectdata.append(projectdata)
        department.projectdata.append(projectdata)
        user.projectdata.append(projectdata)
        
        db.session.add(projectdata)
        db.session.commit()
            
        form.amount.data = ''
        form.observations.data = ''
        form.solution.data = ''
        flash("Project Data added Successfully!")
        return redirect(url_for('system.projectdata')) 
    
    elif carid == None or usersid==None or deparmentsid==None :
        flash("We couldn't add your project data, be sure to add a car, an operation manager and a deparment")
        return redirect(url_for('system.projectdata'))
    
    else:
        flash("We couldn't add your project data, there was a problem")
        return redirect(url_for('system.projectdata'))
   
        

    return redirect(url_for('system.projectdata')) 



@system_blueprint.route('/projectdata/',methods=['GET', 'POST'])
def projectdata():

    form= ProjectDataForm()
    searchForm = SearchForm()

    our_projectdata= ProjectData.query.order_by(ProjectData.id)
    our_cars= Cars.query.order_by(Cars.id)
    our_users= [i for i in Users.query.order_by(Users.id) if str(i.roles)== '[Operations Manager]']
    flash(str(our_projectdata[0].cars.problem))
    our_departments= Departments.query.order_by(Departments.id)
    
    return render_template('system/projectdata.html',our_departments=our_departments,our_users=our_users, our_models=our_projectdata,our_cars=our_cars, form=form, SearchForm=searchForm)


#----------PROJECT DATA----------


@system_blueprint.route('/departments/departmentEdit/<int:id>', methods = ['GET', 'POST'])   
def departmentEdit(id):
    
    form=DepartmentsForm()

    if form.validate_on_submit():
        
        department= Departments.query.get_or_404(id)

        department.description = form.description.data 
        
            
        db.session.add(department)
        db.session.commit()
        
    return redirect(url_for('system.departments'))


@system_blueprint.route('/department/departmentDelete/<int:id>',methods=['GET', 'POST'])
def departmentDelete(id):
    
    form= DepartmentsForm()
    department_to_delete = Department.query.get_or_404(id)
    
    try:
        db.session.delete(department_to_delete)
        db.session.commit()
        flash("Department deleted")
        
        our_deparments=Deparments.query.order_by(Deparments.id)
        return redirect(url_for('system.deparments'))
    except:
        flash('There was a problem deleting your department')
        return redirect(url_for('system.department'))


@system_blueprint.route('/departments/departmentAdd',methods=['POST', 'GET'])
def departmentAdd():
    
    form=DepartmentsForm()
    
    if form.validate_on_submit():

        department = Departments.query.filter_by(description=form.description.data).first()
        if department is None:
            department = Departments(description=form.description.data)
            db.session.add(department)
            db.session.commit()
            
        form.description.data = ''
        flash("Department added Successfully!")
    return redirect(url_for('system.departments'))


@system_blueprint.route('/departments/',methods=['GET', 'POST'])
def departments():

    form=DepartmentsForm()
    searchForm = SearchForm()
    our_departments= Departments.query.order_by(Departments.id)
    
    return render_template('system/departments.html', our_models=our_departments, form=form, SearchForm=searchForm)


#----------DEPARMENTS----------


@system_blueprint.route('/cars/carsDelete/<int:id>',methods=['GET', 'POST'])
def carsDelete(id):
    
    form= CarsForm()
    car_to_delete = Cars.query.get_or_404(id)
    
    try:
        db.session.delete(car_to_delete)
        db.session.commit()
        flash("Car data Deleted")
        
        our_cars=Cars.query.order_by(Cars.id)
        return redirect(url_for('system.cars'))
    except:
        flash('There was a problem deleting your car data')
        return redirect(url_for('system.cars'))


@system_blueprint.route('/cars/carsEdit/<int:id>', methods = ['GET', 'POST'])   
def carsEdit(id):
    
    form=CarsForm()

    if form.validate_on_submit():
        
        car= Cars.query.get_or_404(id)

        car.carID = form.carID.data 
        car.plate = form.plate.data 
        car.brand = form.brand.data 
        car.model = form.model.data 
        car.year = form.year.data 
        car.serialBodywork = form.serialBodywork.data 
        car.serialMotor = form.serialMotor.data 
        car.color = form.color.data 
        car.problem = form.problem.data 
            
        db.session.add(car)
        db.session.commit()
        
    return redirect(url_for('system.cars'))


@system_blueprint.route('/cars/addCars',methods=['GET', 'POST'])
def addCars():
    
    form = CarsForm()
    
    
    if form.validate_on_submit():

        car = Cars.query.filter_by(carID=form.carID.data).first()
        if car is None:
        
            car = Cars( 
                carID=form.carID.data, plate=form.plate.data, brand = form.brand.data,
                model=form.model.data,year=form.year.data, serialBodywork=form.serialBodywork.data, 
                serialMotor=form.serialMotor.data, color=form.color.data,
                problem=form.problem.data
            )
            db.session.add(car)
            db.session.commit()

        form.carID.data = ''
        form.plate.data = ''
        form.brand.data = ''
        form.model.data = ''
        form.year.data = ''
        form.serialBodywork.data = ''
        form.serialMotor.data = ''
        form.color.data = ''
        form.problem.data = ''


        flash("Data car Added Successfully!")

    our_cars = Cars.query.order_by(Cars.id)
    return redirect(url_for('system.cars')) 
    

@system_blueprint.route('/cars/',methods=['GET', 'POST'])
def cars():
    form=CarsForm()
    our_cars = Cars.query.order_by(Cars.id)    
    searchForm=SearchForm()

    return render_template('system/cars.html',form=form, SearchForm=searchForm, our_models=our_cars)


#----------CARS----------


@system_blueprint.route('/customers/customersDelete/<int:id>',methods=['GET', 'POST'])
def customersDelete(id):
    
    form= CustomerForm()
    customers_to_delete = Customers.query.get_or_404(id)
    
    try:
        db.session.delete(customers_to_delete)
        db.session.commit()
        flash("Customer data Deleted")
        
        our_customers=Customers.query.order_by(Customers.id)
        return redirect(url_for('system.customers'))
    except:
        flash('There was a problem deleting your customers data')
        return redirect(url_for('system.customers'))


@system_blueprint.route('/customers/customersEdit/<int:id>', methods = ['GET', 'POST'])   
def customersEdit(id):
    
    form=CustomerForm()
    flash('editando')

    if form.validate_on_submit():

        customer= Customers.query.get_or_404(id)

        customer.name = form.name.data 
        customer.lastName = form.lastName.data 
        customer.dateBirth = form.dateBirth.data 
        customer.description = form.description.data 
        customer.email = form.email.data 
        customer.cellNumber = form.cellNumber.data  
        customer.customerID = form.customerID.data  

        db.session.add(customer)
        db.session.commit()
        return redirect(url_for('system.customers'))


@system_blueprint.route('/customers/customerAdd',methods=['GET', 'POST'])
def customerAdd():
    
    form = CustomerForm()
    
    
    if form.validate_on_submit():

        customer = Customers.query.filter_by(name=form.name.data).first()
        if customer is None:
        
            customer = Customers( 
                name=form.name.data, lastName=form.lastName.data, dateBirth = form.dateBirth.data,
                description=form.description.data,email=form.email.data, cellNumber=form.cellNumber.data,
                customerID=form.customerID.data
            )
            db.session.add(customer)
            db.session.commit()

webapp/templates/Search.html
{% extends 'base.html' %}

{% block content %}


{% for message in get_flashed_messages() %}

	<div class="alert alert-primary alert-dismissible show" role="alert">
		{{message}}
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>	

{% endfor %}

<br/>
		<h1>You search for </h1>

		<br/>

		<!-- TABLE -->

		<table class="table table-hover table" >

			{% for our_model in our_models %}
			<tbody>
				
				{% if page ==  'system.events'%}

				{% include 'system/tables/events-table.html' %}

				{% elif page ==  'system.customers'%}

				{% include 'system/tables/customers-table.html' %}

				{% elif page ==  'system.portfs'%}

				{% include 'system/tables/portfs-table.html' %}
				
				{% elif page ==  'system.cars'%}

				{% include 'system/tables/cars-table.html' %}

				{% elif page ==  'auth.users'%}

				{% include 'auth/users-table.html' %}

				{% else %}
				
				<p>We could find anything</p>

				{%endif%}
			</tbody>
			{%endfor%}
			
		</table>

	
			

		

{% endblock %}

webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href=" {{ url_for('static', filename='css/style.css') }} " rel="stylesheet" >
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
    <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">
  </head>
  <body>{% include 'navbar.html' %}
    <br/>
    <main style="margin-left:45px;">
      <div class="container">
        {% block content %}
        {% endblock %}
      </div>
    </main>
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <script src = "https://code.jquery.com/jquery-3.6.4.js"></script>
    <script src = "https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    {% set the_page= request.url_rule.endpoint%}
    <script>
      
      $(document).ready(function() {

        var models=[];
        
        function loadModels(){
          $.getJSON('/search/{{the_page}}', function(data, status, xhr){
            for (var i = 0; i < data.length; i++ ) {
                  models.push(data[i]);
                  console.log(models)
                  
              }
        });
        };

        loadModels();
        
        
        $('#bar_search').autocomplete({
                source: models, 
                });
          

        }); 
        $('#SearchForm').on('submit', function(e){
          
		$.ajax({
              data: {
                bar_search:$('#bar_search').val(),
                pato:$('#page').val()
              },
              type: 'POST',
              url : '/search/{{the_page}}'
  
            })
            .done(function(html){
              if (html.error){
                $('#result').text(html.error).show();
              }
              else {
                document.write(html)
                
              }
            })

            e.preventDefault();
          });
        
  </script>


    
  </body>
</html>

webapp/templates/cars.html
{% extends 'base.html' %}

{% block content %}


{% for message in get_flashed_messages() %}

	<div class="alert alert-primary alert-dismissible show" role="alert">
		{{message}}
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>	

{% endfor %}

<br/>
		<h1>Car Data </h1>

        {{value}}

		<br/>
		<div class="izq">
			<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target='#document-textModal' >
				Add data car
				<ion-icon name='document-text'></ion-icon>
			</button>
		</div>


		<!-- Modal add-->
        <form method="POST" action="{{url_for('system.addCars')}}">
		<div class="modal fade" id="document-textModal" tabindex="-1" role="dialog" aria-labelledby="document-textModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
				<h5 class="modal-title" id="document-textModalLabel">Add car</h5>
				<button type="button" class="btn btn-light" data-bs-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				</div>
		<div class="modal-body">
	
				
						
                    {{form.hidden_tag()}}
                    
                    <div class="form-group">
                        {{form.carID.label(class="form-control-label")}}
                        {{form.carID(class="form-control form-control")}}
                        <br/>
                        {{form.plate.label(class="form-control-label")}}
                        {{form.plate(class="form-control form-control")}}
                        <br/>
                        {{form.brand.label(class="form-control-label")}}
                        {{form.brand(class="form-control form-control")}}
                        <br/>   
                        {{form.model.label(class="form-control-label")}}
                        {{form.model(class="form-control form-control")}}
                        <br/>
                        {{form.year.label(class="form-control-label")}}
                        {{form.year(class="form-control form-control")}}
                        <br/>
                        {{form.serialBodywork.label(class="form-control-label")}}
                        {{form.serialBodywork(class="form-control form-control")}}
                        <br/>
                        {{form.serialMotor.label(class="form-control-label")}}
                        {{form.serialMotor(class="form-control form-control")}}
                        <br/>
                        {{form.color.label(class="form-control-label")}}
                        {{form.color(class="form-control form-control")}}
                        
                        {{form.problem.label(class="form-control-label")}}
                        {{form.problem(class="form-control form-control")}}
                        <br/>
                        
                    </div>
                </div>
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    {{form.submit(class="btn btn-primary")}}
                </div>
            
			</div>
		</div>
		</div>
    </form>
		<!-- TABLE -->

		<table class="table table-hover table" >
			<thead class="thead">
				
                <tr>
                    {% include 'system/tables-header/cars-tables-header.html' %}
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            
                
			</thead>

			{% for our_model in our_models %}
				<tbody>
			
					<tr>
						{% include 'system/tables/cars-table.html' %}
                            
                        {% include 'system/modals/cars-modals-btn.html' %}
                        
                    </tr>
						
						
				</tbody>
	
			{%endfor%}
</table>


	
			

		

{% endblock %}

webapp/templates/navbar.html
<!--Main Navigation-->
<header>
  <!-- Sidebar -->
  <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-dark">
    <div class="position-sticky ">
      <div class="list-group list-group-flush mx-3 mt-4">
        <a
          href="#"
          class="list-group-item list-group-item-action list-group-item-info"
          aria-current="true"
        >
          <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Dashboard</span>
        </a>
        <a href="{{url_for('auth.users')}}" class="list-group-item list-group-item-action list-group-item-info">
          <i class="fas fa-chart-area fa-fw me-3"></i><span>Users Profile</span>
        </a>
        <a></a>
        <a href="{{url_for('system.portfs')}}" class="list-group-item list-group-item-action list-group-item-info"
          ><i class="fas fa-lock fa-fw me-3"></i><span>Portafolio</span></a
        >
        <a href="{{url_for('system.events')}}" class="list-group-item list-group-item-action list-group-item-info"
          ><i class="fas fa-chart-line fa-fw me-3"></i><span>Events</span></a
        >
        <a href="{{url_for('system.customers')}}"  class="list-group-item list-group-item-action list-group-item-info">
          <i class="fas fa-chart-pie fa-fw me-3"></i><span>Customer Data</span>
        </a>
        <a href="{{url_for('system.cars')}}"  class="list-group-item list-group-item-action list-group-item-info">
          <i class="fas fa-chart-pie fa-fw me-3"></i><span>Car Data</span>
        </a>
        <a href="{{url_for('system.departments')}}"  class="list-group-item list-group-item-action list-group-item-info">
          <i class="fas fa-chart-pie fa-fw me-3"></i><span>Deparments</span>
        </a>
        <a href="{{url_for('system.projectdata')}}"  class="list-group-item list-group-item-action list-group-item-info">
          <i class="fas fa-chart-pie fa-fw me-3"></i><span>Project Data</span>
        </a>
        
        <a href="{{url_for('auth.login')}}"  class="list-group-item list-group-item-action list-group-item-info">
          <i class="fas fa-chart-pie fa-fw me-3"></i><span>Login</span>
        </a>

        
        
      </div>
    </div>
  </nav>
  <!-- Sidebar -->

  <!-- Navbar -->
  <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light  fixed-top">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#sidebarMenu"
        aria-controls="sidebarMenu"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>

      <!-- Brand -->
      
      <a class="container" href="#">
        <img
          src="/static/pics/car.png"
          height="53"
          alt="Logo"
          loading="lazy"
        />
      </a>
      <!-- Search form -->
      {% set page = ['system.customers', 'system.events','system.portfs','system.cars','system.projectdata','system.departments','auth.users'] %}
      {%for i in page %}
      {% if request.url_rule.endpoint == i  %}
     
      <form id="SearchForm" -class="d-none d-md-flex input-group w-auto my-auto" >
        {{SearchForm.hidden_tag()}}
        <div class="center">
        
        <input
        autocomplete="off"
        type="search"
        class="form-control rounded"
        
        placeholder='Search in {{i.replace("system.","").replace("auth.","")}}'
        style="min-width: 225px;"
        id="bar_search"
        />
      </div>
      </form>
      {%endif%}
      {%endfor%}
      
      <!-- Right links -->
      <ul class="navbar-nav ms-auto d-flex flex-row">
        <!-- Notification dropdown -->
        <li class="nav-item dropdown">
          
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
          >
            <li>
              <a class="dropdown-item" href="#">Some news</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Another news</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>

        <!-- Icon -->
        <li class="nav-item">
          <a class="nav-link me-3 me-lg-0" href="#">
            <i class="fas fa-fill-drip"></i>
          </a>
        </li>
        <!-- Icon -->
        <li class="nav-item me-3 me-lg-0">
          <a class="nav-link" href="#">
            <i class="fab fa-github"></i>
          </a>
        </li>

        <!-- Icon dropdown -->
        <li class="nav-item dropdown">
          
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="#"
                ><i class="flag-united-kingdom flag"></i>English
                <i class="fa fa-check text-success ms-2"></i
              ></a>
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-poland flag"></i>Polski</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-china flag"></i>中文</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-japan flag"></i>日本語</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-germany flag"></i>Deutsch</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-france flag"></i>Français</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-spain flag"></i>Español</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-russia flag"></i>Русский</a>
            </li>
            <li>
              <a class="dropdown-item" href="#"><i class="flag-portugal flag"></i>Português</a>
            </li>
          </ul>
        </li>

        <!-- Avatar -->
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            <img
              src="/static/pics/profile_pic_deafult.png"
              class="rounded-circle"
              height="29"
              alt="Avatar"
              loading="lazy"
            />
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
          >
            <li>
              <a class="dropdown-item" href="#">My profile</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Settings</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Logout</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->
</header>
<!--Main Navigation-->

<!--Main layout-->
<main>
  <div class="container pt-4" ></div>
</main>
<!--Main layout-->