webapp/searched/forms.py
from flask_wtf import FlaskForm as Form
from flask_wtf import RecaptchaField
from wtforms import StringField, PasswordField, BooleanField, SubmitField,SelectField
from wtforms.validators import DataRequired, Length, EqualTo, URL

class SearchForm(Form):
    
    bar_search = StringField('Searched:', validators=[DataRequired()])
    submit = SubmitField('Submit')

webapp/__init__.py
from flask import Flask

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from sqlalchemy import create_engine
from sqlalchemy import MetaData


migrate = Migrate()

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))



def page_not_found(error):
    return render_template('404.html'), 404

def create_app(object_name):
    
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    migrate.init_app(app, db, render_as_batch=True)

   

  
    from .system import create_module as system_create_module
    from .auth import create_module as auth_create_module
    from .searched import create_module as searched_create_module
    from .main import create_module as main_create_module
    auth_create_module(app)
    system_create_module(app)
    searched_create_module(app)
    main_create_module(app)

    return app

webapp/main/__init__.py
def create_module(app, **kwargs):
    from .controllers import main_blueprint
    app.register_blueprint(main_blueprint)

webapp/main/controllers.py
from flask import Blueprint, redirect, url_for, render_template

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@main_blueprint.route('/')
def index():
    return redirect(url_for('system.portfs'))

webapp/searched/__init__.py
def create_module(app, **kwargs):
    from .controllers import searched_blueprint
    app.register_blueprint(searched_blueprint)

webapp/searched/controllers.py
from datetime import datetime
from sqlalchemy import desc, func
from flask import render_template, Blueprint, flash, redirect, url_for, current_app, abort, jsonify,request
from flask_login import login_required, current_user
from ..system.models import db, Portfs, Events, Customers, Cars,Departments, ProjectData
from ..auth.models import Users,Role
from ..auth import has_role
from werkzeug.security import generate_password_hash, check_password_hash
from .forms import SearchForm
from ..system.forms import  PortForm, EventsForm, CustomerForm,CarsForm,ProjectDataForm
from sqlalchemy import or_

searched_blueprint = Blueprint(
    'searched',
    __name__,
    template_folder='../templates'
)


@searched_blueprint.context_processor
def base():
    form=SearchForm()
    return dict(form=form)

@searched_blueprint.route('/search/<adress>',methods=['GET', 'POST'])
def search(adress): 
    
    form = SearchForm()
        

    if form.validate_on_submit() or True:
        
        searched = form.bar_search.data
        current_page=str(adress)

        

        models={1:Customers,2:Events,3:Cars,4:Portfs,5:Departments, 6:Users, 7:ProjectData}
        pages={1:'system.customers',2:'system.events',3:'system.cars',4:'system.portfs',5:'system.departments',6:'auth.users',7:'system.projectdata'}

        for key_model in models:
            model = models[key_model]

            for key_page in pages:
                page=pages[key_page]

                if (len(str(searched))> 1) and (current_page==page) and (key_model == key_page) and searched != None: 
                   
                    attrs= dir(model.query.first())          
                    

                    
                    if page == 'auth.users':
                        attrs_filtered = list(filter(lambda x: x.find('_')<0 and not(any([x in ['registry','query','metadata','roles']])), attrs))
                        
                        model_attrs = [[model.query.filter(getattr(model, i).like('%' +searched+'%' )),getattr(model, i)]
                                        for i in attrs_filtered 
                                        if model.query.filter(getattr(model, i).like('%' + searched +'%' )).first() != None]                  
                    else:
                        attrs_filtered = list(filter(lambda x: x.find('_')<0 and not(any([x in ['registry','query','metadata']])), attrs))
                        model_attrs = [[model.query.filter(getattr(model, i).like('%' +searched+'%' )),getattr(model, i)]
                                        for i in attrs_filtered 
                                        if model.query.filter(getattr(model, i).like('%' + searched +'%' )).first() != None]
                    
                    
                    len_model_attrs=[len(i[0].all()) for i in model_attrs]
                    max_index=len_model_attrs.index(max(len_model_attrs))

                    the_attr= model_attrs[max_index][1]
                   
                    
                    models_filtered = model_attrs[max_index][0].order_by(the_attr)
                    
                     
                    return render_template('Search.html', our_models=models_filtered,page=page)
                    
                
                elif searched == None and (current_page==page) and (key_model == key_page):

                    attrs= dir(model.query.first())          
                    attrs_filtered = list(filter(lambda x: x.find('_')<0 and not(any([x in ['registry','query','metadata']])), attrs))

                    all_models = model.query.all()
                    all_category=[]
                    for model in all_models:
                        for attr in attrs_filtered:
                            all_category.append(str(getattr(model, attr)))



                    return jsonify(all_category)

   

webapp/system/__init__.py
def create_module(app, **kwargs):
    from .controllers import system_blueprint
    app.register_blueprint(system_blueprint)

webapp/system/controllers.py
from datetime import datetime
from sqlalchemy import desc, func
from flask import render_template, Blueprint, flash, redirect, url_for, current_app, abort, request
from flask_login import login_required, current_user
from .models import db, Portfs, Events, Customers, Cars, Departments, ProjectData
from ..auth.models import Users,Role
from ..auth import has_role
from werkzeug.security import generate_password_hash, check_password_hash
from ..searched.forms import SearchForm
from .forms import  PortForm, EventsForm, CustomerForm,CarsForm, DepartmentsForm, ProjectDataForm


system_blueprint = Blueprint(
    'system',
    __name__,
    template_folder='../templates'
)


@system_blueprint.route('/projectdata/projectdataDelete/<int:id>',methods=['GET', 'POST'])
def projectdataDelete(id):
    
    form= ProjectDataForm()
    projectdata_to_delete = ProjectData.query.get_or_404(id)
    
    try:
        db.session.delete(projectdata_to_delete)
        db.session.commit()
        flash("Project data deleted")
        
        our_projectdata=ProjectData.query.order_by(ProjectData.id)
        return redirect(url_for('system.projectdata'))
    except:
        flash('There was a problem deleting your event')
        return redirect(url_for('system.projectdata'))


@system_blueprint.route('/projectdata/projectdataAdd',methods=['POST', 'GET'])
def projectdataAdd():
    
    form=ProjectDataForm()
    carid= request.form.get('Cars')
    usersid= request.form.get('Operations Manager')
    deparmentsid= request.form.get('Departments')
    
    if form.validate_on_submit():

        
        
        car = Cars.query.get_or_404(int(carid))
        department = Departments.query.get_or_404(int(deparmentsid))
        user = Users.query.get_or_404(int(usersid))

        projectdata = ProjectData(amount=form.amount.data,observations=form.observations.data, solution=form.solution.data)
        
        car.projectdata.append(projectdata)
        department.projectdata.append(projectdata)
        user.projectdata.append(projectdata)
        
        db.session.add(projectdata)
        db.session.commit()
            
        form.amount.data = ''
        form.observations.data = ''
        form.solution.data = ''
        flash("Project Data added Successfully!")
        return redirect(url_for('system.projectdata')) 
    
    elif carid == None or usersid==None or deparmentsid==None :
        flash("We couldn't add your project data, be sure to add a car, an operation manager and a deparment")
        return redirect(url_for('system.projectdata'))
    
    else:
        flash("We couldn't add your project data, there was a problem")
        return redirect(url_for('system.projectdata'))
   
        

    return redirect(url_for('system.projectdata')) 



@system_blueprint.route('/projectdata/',methods=['GET', 'POST'])
def projectdata():

    form= ProjectDataForm()
    searchForm = SearchForm()

    our_projectdata= ProjectData.query.order_by(ProjectData.id)
    our_cars= Cars.query.order_by(Cars.id)
    our_users= [i for i in Users.query.order_by(Users.id) if str(i.roles)== '[Operations Manager]']
    flash(str(our_projectdata[0].cars.problem))
    our_departments= Departments.query.order_by(Departments.id)
    
    return render_template('system/projectdata.html',our_departments=our_departments,our_users=our_users, our_models=our_projectdata,our_cars=our_cars, form=form, SearchForm=searchForm)


#----------PROJECT DATA----------


@system_blueprint.route('/departments/departmentEdit/<int:id>', methods = ['GET', 'POST'])   
def departmentEdit(id):
    
    form=DepartmentsForm()

    if form.validate_on_submit():
        
        department= Departments.query.get_or_404(id)

        department.description = form.description.data 
        
            
        db.session.add(department)
        db.session.commit()
        
    return redirect(url_for('system.departments'))


@system_blueprint.route('/department/departmentDelete/<int:id>',methods=['GET', 'POST'])
def departmentDelete(id):
    
    form= DepartmentsForm()
    department_to_delete = Department.query.get_or_404(id)
    
    try:
        db.session.delete(department_to_delete)
        db.session.commit()
        flash("Department deleted")
        
        our_deparments=Deparments.query.order_by(Deparments.id)
        return redirect(url_for('system.deparments'))
    except:
        flash('There was a problem deleting your department')
        return redirect(url_for('system.department'))


@system_blueprint.route('/departments/departmentAdd',methods=['POST', 'GET'])
def departmentAdd():
    
    form=DepartmentsForm()
    
    if form.validate_on_submit():

        department = Departments.query.filter_by(description=form.description.data).first()
        if department is None:
            department = Departments(description=form.description.data)
            db.session.add(department)
            db.session.commit()
            
        form.description.data = ''
        flash("Department added Successfully!")
    return redirect(url_for('system.departments'))


@system_blueprint.route('/departments/',methods=['GET', 'POST'])
def departments():

    form=DepartmentsForm()
    searchForm = SearchForm()
    our_departments= Departments.query.order_by(Departments.id)
    
    return render_template('system/departments.html', our_models=our_departments, form=form, SearchForm=searchForm)


#----------DEPARMENTS----------


@system_blueprint.route('/cars/carsDelete/<int:id>',methods=['GET', 'POST'])
def carsDelete(id):
    
    form= CarsForm()
    car_to_delete = Cars.query.get_or_404(id)
    
    try:
        db.session.delete(car_to_delete)
        db.session.commit()
        flash("Car data Deleted")
        
        our_cars=Cars.query.order_by(Cars.id)
        return redirect(url_for('system.cars'))
    except:
        flash('There was a problem deleting your car data')
        return redirect(url_for('system.cars'))


@system_blueprint.route('/cars/carsEdit/<int:id>', methods = ['GET', 'POST'])   
def carsEdit(id):
    
    form=CarsForm()

    if form.validate_on_submit():
        
        car= Cars.query.get_or_404(id)

        car.carID = form.carID.data 
        car.plate = form.plate.data 
        car.brand = form.brand.data 
        car.model = form.model.data 
        car.year = form.year.data 
        car.serialBodywork = form.serialBodywork.data 
        car.serialMotor = form.serialMotor.data 
        car.color = form.color.data 
        car.problem = form.problem.data 
            
        db.session.add(car)
        db.session.commit()
        
    return redirect(url_for('system.cars'))


@system_blueprint.route('/cars/addCars',methods=['GET', 'POST'])
def addCars():
    
    form = CarsForm()
    
    
    if form.validate_on_submit():

        car = Cars.query.filter_by(carID=form.carID.data).first()
        if car is None:
        
            car = Cars( 
                carID=form.carID.data, plate=form.plate.data, brand = form.brand.data,
                model=form.model.data,year=form.year.data, serialBodywork=form.serialBodywork.data, 
                serialMotor=form.serialMotor.data, color=form.color.data,
                problem=form.problem.data
            )
            db.session.add(car)
            db.session.commit()

        form.carID.data = ''
        form.plate.data = ''
        form.brand.data = ''
        form.model.data = ''
        form.year.data = ''
        form.serialBodywork.data = ''
        form.serialMotor.data = ''
        form.color.data = ''
        form.problem.data = ''


        flash("Data car Added Successfully!")

    our_cars = Cars.query.order_by(Cars.id)
    return redirect(url_for('system.cars')) 
    

@system_blueprint.route('/cars/',methods=['GET', 'POST'])
def cars():
    form=CarsForm()
    our_cars = Cars.query.order_by(Cars.id)    
    searchForm=SearchForm()

    return render_template('system/cars.html',form=form, SearchForm=searchForm, our_models=our_cars)


#----------CARS----------


@system_blueprint.route('/customers/customersDelete/<int:id>',methods=['GET', 'POST'])
def customersDelete(id):
    
    form= CustomerForm()
    customers_to_delete = Customers.query.get_or_404(id)
    
    try:
        db.session.delete(customers_to_delete)
        db.session.commit()
        flash("Customer data Deleted")
        
        our_customers=Customers.query.order_by(Customers.id)
        return redirect(url_for('system.customers'))
    except:
        flash('There was a problem deleting your customers data')
        return redirect(url_for('system.customers'))


@system_blueprint.route('/customers/customersEdit/<int:id>', methods = ['GET', 'POST'])   
def customersEdit(id):
    
    form=CustomerForm()
    flash('editando')

    if form.validate_on_submit():

        customer= Customers.query.get_or_404(id)

        customer.name = form.name.data 
        customer.lastName = form.lastName.data 
        customer.dateBirth = form.dateBirth.data 
        customer.description = form.description.data 
        customer.email = form.email.data 
        customer.cellNumber = form.cellNumber.data  
        customer.customerID = form.customerID.data  

        db.session.add(customer)
        db.session.commit()
        return redirect(url_for('system.customers'))


@system_blueprint.route('/customers/customerAdd',methods=['GET', 'POST'])
def customerAdd():
    
    form = CustomerForm()
    
    
    if form.validate_on_submit():

        customer = Customers.query.filter_by(name=form.name.data).first()
        if customer is None:
        
            customer = Customers( 
                name=form.name.data, lastName=form.lastName.data, dateBirth = form.dateBirth.data,
                description=form.description.data,email=form.email.data, cellNumber=form.cellNumber.data,
                customerID=form.customerID.data
            )
            db.session.add(customer)
            db.session.commit()

webapp/templates/system/customers-modals-btn.html
<!--Edit Button-->
<td>
<button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#editModal{{our_model.id}}">
  <ion-icon name="create-outline"></ion-icon>
</button>
</td>

<!--Edit Modal-->		
<td>
<form class="row g-3" method="POST" action="{{url_for('system.customersEdit', id=our_model.id)}}"></form>
<div class="modal fade" id="editModal{{our_model.id}}" tabindex="-1" role="dialog" aria-labelledby="createModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
  <div class="modal-content ">
    <div class="modal-header">
    <h5 class="modal-title" id="createModalLabel">Edit Customer</h5>
    <button type="button" class="btn btn-light" data-bs-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    </div>
    <div class="modal-body">
      
            
            {{form.hidden_tag()}}
            <div class="form-group">
                        
              {{form.name.label(class="form-control-label")}}
              {{form.name(class="form-control form-control" , value=our_model.name)}}
              <br/>
              {{form.lastName.label( class="form-control-label")}}
              {{form.lastName(class="form-control form-control" , value=our_model.lastName)}}
              <br/>
              {{form.dateBirth.label(class="form-control-label")}}
              {{form.dateBirth(class="form-control form-control" , value=our_model.dateBirth)}}
              <br/>
              {{form.description.label( class="form-control-label")}}
              {{form.description(class="form-control form-control" , value=our_model.description)}}
              <br/>
              {{form.email.label( class="form-control-label")}}
              {{form.email(class="form-control form-control" , value=our_model.email)}}
              <br/>
              {{form.cellNumber.label( class="form-control-label")}}
              {{form.cellNumber(class="form-control form-control" , value=our_model.cellNumber)}}
              <br/>
              {{form.customerID.label( class="form-control-label")}}
              {{form.customerID(class="form-control form-control" , value=our_model.customerID)}}
              <br/>
            
        
            </div>
            <div class="modal-footer text-center">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              {{form.submit(class="btn btn-primary")}}
            </div>
          
  </div>

  </div>
</div>
</form>
</td>

<!--Delete Button-->
<td>
  
    <button type="submit" class="btn btn-light" >
    <a href="{{url_for('system.customersDelete', id=our_model.id)}}">
      {{form.hidden_tag()}}
      <ion-icon name='close'></ion-icon>
    </a>
  </button>
  
</td>

webapp/templates/system/customers.html
{% extends 'base.html' %}

{% block content %}


{% for message in get_flashed_messages() %}

	<div class="alert alert-primary alert-dismissible show" role="alert">
		{{message}}
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>	

{% endfor %}

<br/>
		<h1>Customer Data </h1>

		<br/>
		<div class="izq">
			<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target='#document-textModal' >
				Add a customer
				<ion-icon name='document-text'></ion-icon>
			</button>
		</div>


		<!-- Modal add-->
        
		<div class="modal fade" id="document-textModal" tabindex="-1" role="dialog" aria-labelledby="document-textModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
				<h5 class="modal-title" id="document-textModalLabel">Add customer</h5>
				<button type="button" class="btn btn-light" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				</div>
		<div class="modal-body">
	
				
			<form method="POST" action="{{url_for('system.customerAdd')}}">
                    {{form.hidden_tag()}}
                    
                      <div class="form-group">

                        {{form.name.label(class="form-control-label")}}
                        {{form.name(class="form-control form-control")}}
                        <br/>
                        {{form.lastName.label( class="form-control-label")}}
                        {{form.lastName(class="form-control form-control")}}
                        <br/>
                        {{form.dateBirth.label(class="form-control-label")}}
                        {{form.dateBirth(class="form-control form-control")}}
                        <br/>
                        {{form.description.label( class="form-control-label")}}
                        {{form.description(class="form-control form-control")}}
                        <br/>
                        {{form.email.label( class="form-control-label")}}
                        {{form.email(class="form-control form-control")}}
                        <br/>
                        {{form.cellNumber.label( class="form-control-label")}}
                        {{form.cellNumber(class="form-control form-control")}}
                        <br/>
                        {{form.customerID.label( class="form-control-label")}}
                        {{form.customerID(class="form-control form-control")}}
                        <br/>
                        
                    </div>
                </div>
                
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    {{form.submit(class="btn btn-primary")}}
                </div>
            </form>
				

				</div>
			</div>
		</div>
		</div>

		<!-- TABLE -->

		<table class="table table-hover table" >
			<thead class="thead">
				
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col">Last Name</th>
                      <th scope="col">Date Birth</th>
                      <th scope="col">Description</th>
                      <th scope="col">Email</th>
                      <th scope="col">Cell Number</th>
                      <th scope="col">ID</th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                      </tr>
                
			</thead>

			{% for our_model in our_models %}
				<tbody>
			
					<tr>
                        {% include 'system/tables/customers-table.html' %}
                    
                        {% include 'system/modals/customers-modals-btn.html' %}
                    
                    
                    </tr>
						
						
				</tbody>
	
			{%endfor%}
</table>


	
			

		

{% endblock %}

webapp/templates/system/departments.html
{% extends 'base.html' %}

{% block content %}


{% for message in get_flashed_messages() %}

	<div class="alert alert-primary alert-dismissible show" role="alert">
		{{message}}
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>	

{% endfor %}

<br/>
		<h1>Department </h1>

		<br/>
		<div class="izq">
			<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target='#document-textModal' >
				Add a department
				<ion-icon name='document-text'></ion-icon>
			</button>
		</div>


		<!-- Modal add-->
        <form method="POST" action="{{url_for('system.departmentAdd')}}">
		<div class="modal fade" id="document-textModal" tabindex="-1" role="dialog" aria-labelledby="document-textModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
				<h5 class="modal-title" id="document-textModalLabel">Add deparment</h5>
				<button type="button" class="btn btn-light" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				</div>
		<div class="modal-body">
	
				
						
                    {{form.hidden_tag()}}
                    
                    
                    <div class="form-group">

                        {{form.description.label(class="form-control-label")}}
                        {{form.description(class="form-control form-control")}}
                        <br/>
                    
                        
                    </div>
                </div>
                
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    {{form.submit(class="btn btn-primary")}}
                </div>

				

				</div>
			</div>
		</div>
		</div>
    </form>
		<!-- TABLE -->

		<table class="table table-hover table" >
			<thead class="thead">
				
                    <tr>
						<th scope="col">#</th>
						{% include 'system/tables-header/departments-tables-header.html' %}
                      <th scope="col"></th>
					  <th scope="col"></th>
                      </tr>
                
			</thead>

			{% for our_model in our_models %}
				<tbody>
			
					<tr>
						<th scope="row">{{our_model.id}}</th>
                        {% include 'system/tables/departments-table.html' %}
                    
                        {% include 'system/modals/departments-modals-btn.html' %}
                    
                    
                    </tr>
						
						
				</tbody>
	
			{%endfor%}
</table>


	
			

		

{% endblock %}

webapp/templates/system/projectdata.html
{% extends 'base.html' %}

{% block content %}


{% for message in get_flashed_messages() %}

	<div class="alert alert-primary alert-dismissible show" role="alert">
		{{message}}
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>	

{% endfor %}

<br/>
		<h1>Project Data </h1>

		<br/>
		<div class="izq">
			<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target='#document-textModal' >
				Add project data 
				<ion-icon name='document-text'></ion-icon>
			</button>
		</div>


		<!-- Modal add-->
<form method="POST" action="{{url_for('system.projectdataAdd')}}">
		<div class="modal fade" id="document-textModal" tabindex="-1" role="dialog" aria-labelledby="document-textModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
				<h5 class="modal-title" id="document-textModalLabel">Modal</h5>
				<button type="button" class="btn btn-light" data-bs-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				</div>
		<div class="modal-body">
	
					{{form.hidden_tag()}}
						
					<div class="form-group">
						{% set models =
							{'Cars':[our_cars,'system/tables-header/cars-tables-header.html','system/tables/cars-table.html'],
							 'Operations Manager':[our_users,'auth/users-tables-header.html','auth/users-table.html'],
							 'Departments':[our_departments,'system/tables-header/departments-tables-header.html','system/tables/departments-table.html']
							} 
						%}
						

						{%for key in models%}	
						{%set values=models[key]%}
						<div class="dropdown">
							
							{{key}}:
							<button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							  </button>
							<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
							<div class="dropdown-header">
								<table class="table table-dropdown">
									<thead class="thead-light">
									<tr>
										<th scope="col">Options</th>
										{% include values[1] %}
									</tr>
									</thead>		
										{%for our_model in values[0]%}
									<tbody>
						
									<tr>	
										<td >	
										<div class="form-check">
											
										<input type="checkbox" class="form-check-input" name="{{key}}" value="{{our_model.id}}" onClick="ckChange(this)">
										<label class="form-check-label" for="dropdownCheck"></label> 
										
										</div>
										</td>
						
										{% include values[2]  %}
								
									</tr>
									<script type="text/javascript">
										function ckChange(el) {
								var ckName = document.getElementsByName(el.name);
								for (var i = 0, c; c = ckName[i]; i++) {
								c.disabled = !(!el.checked || c === el);
								}
								}
								</script>
									</tbody>
									{%endfor%}
									
									</table>
						</div>
						</div>
						</div>
						<br/>
						{%endfor%}


					
						<br/>
						{{form.solution.label(class="form-control-label")}}
						{{form.solution(class="form-control form-control")}}
						<br/>
						{{form.amount.label(class="form-control-label")}}
						{{form.amount(class="form-control form-control")}}
						<br/>
						{{form.observations.label(class="form-control-label")}}
						{{form.observations(class="form-control form-control")}}
						<br/>

					</div>
					
					</div>

					<div class="modal-footer text-center">
						<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
						{{form.submit(class="btn btn-primary")}}
					</div>

				

				</div>
			</div>
		</div>
	</form>

		<!-- TABLE -->

		<table class="table table-hover table" >
			<thead class="thead">
				<tr>
					<th scope="col">Id</th>
					<th scope="col">Car</th>
					<th scope="col">Department</th>
					<th scope="col">Operation Manager</th>
					<th scope="col">Problem</th>
					<th scope="col">Solution</th>
					<th scope="col">Amount</th>
					<th scope="col">Observations</th>
					<th scope="col"></th>
					<th scope="col"></th>
					<th scope="col"></th>
				</tr>
			</thead>

			{% for our_model in our_models %}
				<tbody>
			
					<tr>
						{% include 'system/tables/projectdata-table.html' %}
						<td>{% include 'system/modals/projectdata-modal-btns.html' %}</td>
						
						</tr>
				</tbody>
	
			{%endfor%}
</table>

	
			

		

{% endblock %}